openapi: 3.0.1.

info:
  version: '1.0.0'
  title: 'PinkFilm API'
  x-logo:
    url: './logo-pink-film.svg'

servers:
  - url: 'https://server_ip'
    description: 'Production Server'

tags:
  - name: 'situation'
  - name: 'user'

security:
  - passwordAutentication: []

paths:
  /situations:
    get:
      tags:
        - 'situation'
      summary: 'Endpoint for retrieve platform situations'
      parameters:
        $ref: './parameters/situation-list.json'
      responses:
        200:
          description: 'Get the situations that upload the users'
          content:
            application/json:
              schema:
                type: 'array'
                items:
                  $ref: './schemas/situation-list.json'
  /oauth/token:
    post:
      tags:
        - 'user'
      summary: 'Endpoint for auth user'
      requestBody:
        description: 'Get bearer token from user/pass'
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/oauth-token.json'
      responses:
        200:
          description: 'Get the token for auth'
          content:
            application/json:
              schema:
                $ref: './schemas/token.json'

components:
  securitySchemes:
    passwordAutentication:
      type: oauth2
      flows:
        password:
          tokenUrl: /oauth/token
          scopes: {}
